name: deepu-work
on: push
jobs:

    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: logout
          run: docker logout
             

        - name: Login to Docker Hub
          run: docker build -t deepik/ngin:latest .

        - name: push to docker hub
          run: |
            docker login -u "Deepik89" -p "janya1234"
            docker push deepik/ngin:latest

