name: deepu-work
on: push
jobs:

    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: logout
          run: docker logout
             

        - name: docker login
          run: |
             echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
             docker build -t deepik89/node-app:latest .
               
    
             docker push deepik89/node-app:latest 

