name: deepu-work
on: push
jobs:

    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: logout
          run: docker logout
             

        - name: Login to Docker Hub
          run: docker logout

        - name: push to docker hub
          run: |
            docker build -t Deepik89/ngiwen:v1 .
            docker login docker.io -u "ivaan9658@gmail.com" -p ${{ secrets.DOCKER_TOKEN }}
            docker push Deepik89/ngiwen:v1

