name: deepu-work
on: push
env:
    Node_Version: '18'
jobs:

    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: docker login
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
           
        - name: build and push docker image  
          run: docker build -t deepik89/node-app:latest .
               
        - name: push
          run: docker push deepik89/node-app:latest 

